[CmdletBinding()]
param([string]$RepoRoot = (Split-Path -Parent $PSScriptRoot))

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem
$root = (Resolve-Path -LiteralPath $RepoRoot).Path
$head = (& git -C $root rev-parse HEAD).Trim(); $branch = (& git -C $root branch --show-current).Trim()
$temp = Join-Path ([IO.Path]::GetTempPath()) ('review-packet-test-' + [guid]::NewGuid()); New-Item -ItemType Directory -Path $temp | Out-Null

function Add-File([string]$Path, [string]$Text) { $target=Join-Path $temp $Path;New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target)|Out-Null;Set-Content -LiteralPath $target -Value $Text -NoNewline }
function Pin([string]$Path = 'docs/architecture.md') { @{ repository_path = $Path; sha256 = (Get-FileHash -LiteralPath (Join-Path $root $Path) -Algorithm SHA256).Hash.ToLowerInvariant() } }
function Authority-Pins { @('docs/architecture.md','docs/simulation_model.md','docs/simulation_principles.md','docs/roadmap.md','docs/decisions.md') | ForEach-Object { Pin $_ } }
function Brief([string]$Request = 'Accept the completed package.') { "## Review Type`nCapability-cluster review`n## Review Purpose`nReview a completed package and decide whether its stricter evidence boundary is ready for future owner decisions.`n## Authoritative Repository State`nThe repository architecture, simulation model, simulation principles, roadmap, and decisions remain authoritative.`n## Plain-Language Outcome`n1. The package completed a fail-closed review-packet boundary.`n2. It works by rejecting missing, stale, inconsistent, and shallow decision evidence.`n3. The risk found was review ambiguity rather than engine behavior.`n4. The game can now rely on clearer architecture-review evidence before future capability selection.`n5. The next work should remain deferred until the owner chooses a bounded gameplay capability.`n## Decision Card`n| Question | Answer |`n|---|---|`n| Recommended capability | Defer a separately selected gameplay capability pending owner direction |`n| Why now | The review-safety boundary is complete and independently testable |`n| Player or project value | Owners receive decision evidence that cannot silently omit required context |`n| Technical risk | Low |`n| Persistence impact | None |`n| New ADR | Not required |`n| Expected scope | Health check |`n| Major alternatives deferred | Gameplay capability selection and generic document infrastructure |`n## Decision Requested`nThe review is ready for one owner decision.`n## Owner Decision Request`n$Request" }
function Scenario([int]$Count = 1) { $block = "## Scenario`n### Initial State`nA compact package-review archive contains completion evidence but no architecture decision context.`n### Trigger`nThe owner requests a post-package architecture review that must support one explicit decision.`n### Authoritative State Transitions`nNo game state changes; the validator only evaluates the packet boundary and authoritative pins.`n### Causal History`nThe review profile links the brief, maps, scenario, source pins, Git identity, and completed package records.`n### Player-Facing Projection`nThere is no player-facing projection because this package changes review safety rather than game behavior.`n### Decision Relevance`nThe owner can distinguish completion evidence from a decision-ready packet and defer the next capability safely."; (@(1..$Count | ForEach-Object { $block }) -join "`n`n") }
function DependencyMap { "## Capability Dependencies`nThe phase decision must account for the explicit dependencies that preserve the review-packet safety boundary.`n`n| Capability | Dependencies | Decision Relevance |`n|---|---|---|`n| Phase profile approval | Five authoritative sources and two structured scenarios | Prevents sequencing a phase decision without repository authority and tested scenario context |" }
function AdrIndex { "## ADR Index`nThe phase review identifies the governing architecture decisions before selecting work that could alter ownership boundaries.`n`n| ADR Identifier | Status | Decision Relevance |`n|---|---|---|`n| ADR-041 | Accepted | Defines the existing atomicity boundary that the proposed phase must preserve |" }
function PhaseContext { "## Unresolved Phase Questions`nWhich bounded capability can advance project value without widening the established simulation and persistence boundaries?`n## Alternatives`nDefer gameplay selection, choose a single bounded capability, or request deeper architecture review before staging work.`n## Decision Context`nThe owner needs dependency and ADR context to decide whether a phase can proceed while review-packet validation remains workflow-only." }
function Seed-Files { Add-File package.md 'Completed package record.'; Add-File sprint.md 'Completed sprint record.'; Add-File verify.md 'Command: fixture; Exit code: 0; Outcome: PASS.'; Add-File git.md "branch: $branch`nHEAD: $head`nstatus: fixture"; Add-File map.md 'Authoritative repository sources: architecture, simulation model, simulation principles, roadmap, and decisions. The architecture snapshot records that packet validation is workflow-only, preserves engine and persistence boundaries, and adds no runtime authority. The simulation capability map records that no truth, transition, perception, narration, or player-facing behavior changes. Current and deferred capabilities remain controlled by the roadmap and owner decisions.'; Add-File brief.md (Brief); Add-File scenario.md (Scenario 2); Add-File dependencies.md (DependencyMap); Add-File adr.md (AdrIndex); Add-File phase.md (PhaseContext); foreach($copy in @(@('authority/architecture.md','docs/architecture.md'),@('authority/simulation.md','docs/simulation_model.md'),@('authority/simulation_principles.md','docs/simulation_principles.md'),@('authority/roadmap.md','docs/roadmap.md'),@('authority/decisions.md','docs/decisions.md'))){$target=Join-Path $temp $copy[0];New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target)|Out-Null;Copy-Item -LiteralPath (Join-Path $root $copy[1]) -Destination $target -Force} }
function New-Definition([string]$Profile) {
    $members = @(@{source_path='package.md';path='records/package.md';role='package_record';artifact_kind='evidence'},@{source_path='sprint.md';path='records/sprint.md';role='sprint_record';artifact_kind='evidence'},@{source_path='verify.md';path='evidence/verification.md';role='verification_evidence';artifact_kind='evidence'},@{source_path='git.md';path='evidence/git.md';role='git_evidence';artifact_kind='evidence'})
    if($Profile -ne 'package-review'){$members+=@(@{source_path='brief.md';path='review/brief.md';role='owner_review_brief';artifact_kind='packet_synthesis';sources=@(Authority-Pins)},@{source_path='map.md';path='review/architecture.md';role='architecture_snapshot';artifact_kind='packet_synthesis';sources=@(Authority-Pins)},@{source_path='map.md';path='review/simulation.md';role='simulation_capability_map';artifact_kind='packet_synthesis';sources=@(Authority-Pins)},@{source_path='scenario.md';path='review/scenarios.md';role='simulation_scenarios';artifact_kind='packet_synthesis';sources=@(Authority-Pins)},@{source_path='authority/architecture.md';path='sources/architecture.md';role='authoritative_architecture_source';artifact_kind='authoritative_source';repository_path='docs/architecture.md'},@{source_path='authority/simulation.md';path='sources/simulation.md';role='authoritative_simulation_source';artifact_kind='authoritative_source';repository_path='docs/simulation_model.md'},@{source_path='authority/simulation_principles.md';path='sources/simulation_principles.md';role='authoritative_simulation_principles_source';artifact_kind='authoritative_source';repository_path='docs/simulation_principles.md'},@{source_path='authority/roadmap.md';path='sources/roadmap.md';role='authoritative_roadmap_source';artifact_kind='authoritative_source';repository_path='docs/roadmap.md'},@{source_path='authority/decisions.md';path='sources/decisions.md';role='authoritative_decision_source';artifact_kind='authoritative_source';repository_path='docs/decisions.md'})}
    if($Profile -eq 'phase-architecture-review'){$members+=@(@{source_path='dependencies.md';path='review/dependencies.md';role='capability_dependency_map';artifact_kind='packet_synthesis';sources=@(Authority-Pins)},@{source_path='adr.md';path='review/adr.md';role='architecture_decision_index';artifact_kind='packet_synthesis';sources=@(Authority-Pins)},@{source_path='phase.md';path='review/phase.md';role='phase_decision_context';artifact_kind='packet_synthesis';sources=@(Authority-Pins)})}
    [pscustomobject]@{profile=$Profile;packet_id='fixture';review_identity='fixture';reviewed_head=$head;creation_source_state=@{branch=$branch;head=$head;status='fixture'};members=$members;verification_evidence_path='evidence/verification.md';git_evidence_path='evidence/git.md'}
}
function Write-Definition($Definition,[string]$Name){$path=Join-Path $temp "$Name.json";$Definition|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $path -NoNewline;$path}
function Assemble($Definition,[string]$Name){$zip=Join-Path $temp "$Name.zip";& (Join-Path $root 'tools/assemble_review_packet.ps1') -DefinitionPath (Write-Definition $Definition $Name) -OutputPath $zip;$zip}
function Assert-Rejected([string]$Name,[string]$Expected,[scriptblock]$Action){try{& $Action}catch{if($_.Exception.Message-notmatch('(?i)'+[regex]::Escape($Expected))){throw "$Name unexpected message: $($_.Exception.Message)"};Write-Output "PASS expected rejection: $Name";return};throw "$Name unexpectedly passed"}
function New-RawZip([string]$Name,[string[]]$Entries){$zip=Join-Path $temp "$Name.zip";$archive=[IO.Compression.ZipFile]::Open($zip,[IO.Compression.ZipArchiveMode]::Create);try{foreach($entry in $Entries){[void]$archive.CreateEntry($entry)}}finally{$archive.Dispose()};$zip}
function Read-ZipText([string]$Zip,[string]$Entry){$archive=[IO.Compression.ZipFile]::OpenRead($Zip);try{$reader=[IO.StreamReader]::new($archive.GetEntry($Entry).Open());try{return $reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$archive.Dispose()}}
function Replace-ZipText([string]$Zip,[string]$Entry,[string]$Text){$archive=[IO.Compression.ZipFile]::Open($Zip,[IO.Compression.ZipArchiveMode]::Update);try{$archive.GetEntry($Entry).Delete();$writer=[IO.StreamWriter]::new($archive.CreateEntry($Entry).Open());try{$writer.Write($Text)}finally{$writer.Dispose()}}finally{$archive.Dispose()}}
function Add-ZipEntry([string]$Zip,[string]$Entry){$archive=[IO.Compression.ZipFile]::Open($Zip,[IO.Compression.ZipArchiveMode]::Update);try{[void]$archive.CreateEntry($Entry)}finally{$archive.Dispose()}}
function Remove-ZipEntry([string]$Zip,[string]$Entry){$archive=[IO.Compression.ZipFile]::Open($Zip,[IO.Compression.ZipArchiveMode]::Update);try{$archive.GetEntry($Entry).Delete()}finally{$archive.Dispose()}}

try {
    Seed-Files
    foreach($profile in @('package-review','post-package-architecture-review','phase-architecture-review')){& (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition $profile) $profile) -RepoRoot $root}
    Assert-Rejected 'unsupported profile' 'Unsupported profile' { Assemble (New-Definition 'invalid-profile') 'invalid-profile' | Out-Null }
    Assert-Rejected 'missing manifest normal mode' 'manifest absent' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (New-RawZip 'missing-manifest' @('evidence.txt')) }
    Assert-Rejected 'normal-mode legacy rejection' 'manifest absent' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (New-RawZip 'legacy-normal' @('legacy.txt')) }; & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (New-RawZip 'legacy-ok' @('legacy.txt')) -Legacy
    $schemaZip=Assemble (New-Definition 'package-review') 'bad-schema';Replace-ZipText $schemaZip 'review_packet_manifest.json' ((Read-ZipText $schemaZip 'review_packet_manifest.json') -replace '"schema_version":\s*"1.0.0"','"schema_version":"9.9.9"');Assert-Rejected 'unsupported schema' 'unsupported schema' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath $schemaZip }
    $extraZip=Assemble (New-Definition 'package-review') 'undeclared-member';Add-ZipEntry $extraZip 'undeclared.md';Assert-Rejected 'undeclared archive member' 'manifest membership mismatch' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath $extraZip }
    $absentZip=Assemble (New-Definition 'package-review') 'absent-member';Remove-ZipEntry $absentZip 'records/package.md';Assert-Rejected 'absent declared member' 'manifest membership mismatch' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath $absentZip }
    $hashZip=Assemble (New-Definition 'package-review') 'hash-tamper';Replace-ZipText $hashZip 'records/package.md' 'tampered';Assert-Rejected 'member checksum tamper' 'hash records/package.md' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath $hashZip }
    $selfZip=Assemble (New-Definition 'package-review') 'self-tamper';Replace-ZipText $selfZip 'review_packet_manifest.json' ((Read-ZipText $selfZip 'review_packet_manifest.json') -replace '"sha256":\s*"[0-9a-f]{64}"','"sha256":"0000000000000000000000000000000000000000000000000000000000000000"');Assert-Rejected 'manifest self hash tamper' 'manifest self hash' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath $selfZip }
    $missingRole=New-Definition 'package-review';$missingRole.members=@($missingRole.members|Where-Object {$PSItem['role'] -ne 'git_evidence'});Assert-Rejected 'missing required member' 'required role count git_evidence' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $missingRole 'missing-role') }
    $postMissingScenario=New-Definition 'post-package-architecture-review';$postMissingScenario.members=@($postMissingScenario.members|Where-Object {$PSItem['role'] -ne 'simulation_scenarios'});Assert-Rejected 'post profile missing scenarios' 'required role count simulation_scenarios' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $postMissingScenario 'post-no-scenario') }
    $phaseMissingContext=New-Definition 'phase-architecture-review';$phaseMissingContext.members=@($phaseMissingContext.members|Where-Object {$PSItem['role'] -notin @('capability_dependency_map','architecture_decision_index','phase_decision_context')});Assert-Rejected 'phase missing dependency and ADR context' 'required role count capability_dependency_map' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $phaseMissingContext 'phase-no-context') }
    Add-File dependencies.md "## Capability Dependencies`nA dependency map is required for this phase.`n`n| Capability | Dependencies | Decision Relevance |`n|---|---|---|";Assert-Rejected 'shallow phase dependency map' 'phase dependency row' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'phase-architecture-review') 'shallow-dependencies') -RepoRoot $root };Seed-Files
    Add-File adr.md "## ADR Index`nAn ADR index is required for this phase.`n`n| ADR Identifier | Status | Decision Relevance |`n|---|---|---|";Assert-Rejected 'shallow phase ADR index' 'phase ADR row' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'phase-architecture-review') 'shallow-adr') -RepoRoot $root };Seed-Files
    Add-File phase.md "## Unresolved Phase Questions`nToo short.`n## Alternatives`nToo short.`n## Decision Context`nToo short.";Assert-Rejected 'shallow phase decision context' 'shallow phase decision context' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'phase-architecture-review') 'shallow-phase-context') -RepoRoot $root };Seed-Files
    Add-File dependencies.md (AdrIndex);Assert-Rejected 'wrong-role phase content' 'phase heading ## Capability Dependencies' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'phase-architecture-review') 'wrong-phase-role') -RepoRoot $root };Seed-Files
    $missingPrinciples=New-Definition 'post-package-architecture-review';$missingPrinciples.members=@($missingPrinciples.members|Where-Object {$PSItem['role'] -ne 'authoritative_simulation_principles_source'});Assert-Rejected 'missing simulation-principles authority' 'required role count authoritative_simulation_principles_source' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $missingPrinciples 'missing-principles') }
    $kind=New-Definition 'post-package-architecture-review';$kind.members[4]['artifact_kind']='evidence';Assert-Rejected 'invalid role artifact kind' 'invalid role/artifact-kind owner_review_brief' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $kind 'bad-kind') }
    $outside=New-Definition 'package-review';$outside.members+=@{source_path='map.md';path='review/scenarios.md';role='simulation_scenarios';artifact_kind='packet_synthesis';sources=@(Pin)};Assert-Rejected 'package profile boundary' 'role outside profile simulation_scenarios' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $outside 'profile-boundary') }
    $noPins=New-Definition 'post-package-architecture-review';$noPins.members[4]['sources']=$null;Assert-Rejected 'missing source pins' 'source pins review/brief.md' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $noPins 'no-pins') }
    $missingSource=New-Definition 'post-package-architecture-review';$missingSource.members[5]['sources']=@(@{repository_path='docs/not-present.md';sha256=('0'*64)});Assert-Rejected 'missing repository source' 'source missing docs/not-present.md' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $missingSource 'missing-source') -RepoRoot $root }
    $wrongAuthority=New-Definition 'post-package-architecture-review';$wrongAuthority.members[9]['source_path']='map.md';Assert-Rejected 'authoritative role contains wrong source' 'authoritative member mismatch authoritative_simulation_source' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $wrongAuthority 'wrong-authority') -RepoRoot $root }
    Add-File 'authority/simulation_principles.md' 'Generic text that is not the simulation-principles authority.';$genericAuthority=New-Definition 'post-package-architecture-review';Assert-Rejected 'required authority replaced with generic text' 'authoritative member mismatch authoritative_simulation_principles_source' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $genericAuthority 'generic-authority') -RepoRoot $root };Seed-Files
    $missingAuthorityPin=New-Definition 'post-package-architecture-review';foreach($member in @($missingAuthorityPin.members|Where-Object {$PSItem['artifact_kind'] -eq 'packet_synthesis'})){$member['sources']=@($member['sources']|Where-Object {$PSItem['repository_path'] -ne 'docs/simulation_principles.md'})};Assert-Rejected 'required authority absent from synthesis pins' 'synthesis authority pin docs/simulation_principles.md' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $missingAuthorityPin 'missing-authority-pin') -RepoRoot $root }
    $unbundledPin=New-Definition 'post-package-architecture-review';$unbundledPin.members[4]['sources']=@((Authority-Pins)+(Pin 'docs/current_sprint.md'));Assert-Rejected 'source pin not backed by bundled authority' 'unbundled synthesis pin docs/current_sprint.md' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $unbundledPin 'unbundled-pin') -RepoRoot $root }
    Add-File package.md ' ';Assert-Rejected 'blank package record' 'non-substantive package_record' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'package-review') 'blank-package') };Add-File package.md 'Completed package record.'
    Add-File verify.md 'PASS';Assert-Rejected 'placeholder verification evidence' 'non-substantive verification_evidence' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'package-review') 'placeholder-verify') };Add-File verify.md 'Command: fixture; Exit code: 0; Outcome: PASS.'
    Add-File brief.md (Brief ' ');Assert-Rejected 'empty decision request' 'non-substantive brief section' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'empty-decision') };Add-File brief.md ((Brief)+"`n## Owner Decision Request`nAccept again.");Assert-Rejected 'multiple decision requests' 'brief heading ## Owner Decision Request' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'two-decisions') };Add-File brief.md (Brief)
    Add-File brief.md '## Review Type';Assert-Rejected 'missing review brief sections' 'non-substantive brief section' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'missing-brief-sections') };Add-File brief.md (Brief 'TODO');Assert-Rejected 'placeholder review brief' 'non-substantive brief section' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'placeholder-brief') };Add-File brief.md (Brief)
    Add-File brief.md ((Brief)-replace 'Technical risk | Low','Technical risk | Safe reviews');Assert-Rejected 'vague Decision Card value' 'invalid decision card row Technical risk' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'vague-card') };Add-File brief.md (Brief)
    Add-File map.md 'Authoritative repository sources.';Assert-Rejected 'shallow architecture and simulation maps' 'shallow architecture_snapshot' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'shallow-maps') };Seed-Files
    Add-File scenario.md '## Scenario';Assert-Rejected 'incomplete scenario headings' 'scenario heading ### Initial State' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'bad-scenario') };Add-File scenario.md (Scenario 1);Assert-Rejected 'insufficient phase scenarios' 'phase scenario count' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'phase-architecture-review') 'one-phase-scenario') };Add-File scenario.md (Scenario 2)
    Add-File scenario.md ((Scenario 1)-replace 'There is no player-facing projection because this package changes review safety rather than game behavior.','None.');Assert-Rejected 'non-substantive scenario subsection' 'shallow scenario section ### Player-Facing Projection' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'post-package-architecture-review') 'shallow-scenario') };Add-File scenario.md (Scenario 2)
    Add-File git.md "branch: $branch`nHEAD: $('0'*40)`nstatus: fixture";Assert-Rejected 'git evidence head inconsistency' 'git evidence identity mismatch' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble (New-Definition 'package-review') 'bad-git') };Add-File git.md "branch: $branch`nHEAD: $head`nstatus: fixture"
    $candidateMismatch=New-Definition 'package-review';$candidateMismatch.reviewed_head=('0'*40);$candidateMismatch.creation_source_state.head=('0'*40);Add-File git.md "branch: $branch`nHEAD: $('0'*40)`nstatus: fixture";Assert-Rejected 'candidate repository head inconsistency' 'candidate repository HEAD mismatch' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $candidateMismatch 'candidate-mismatch') -RepoRoot $root };Add-File git.md "branch: $branch`nHEAD: $head`nstatus: fixture"
    foreach($case in @(@('absolute path','C:/bad.md','Unsafe'),@('backslash path','review\\brief.md','Unsafe'),@('empty segment path','review//brief.md','Unsafe'))){$pathCase=New-Definition 'package-review';$pathCase.members[0]['path']=$case[1];Assert-Rejected $case[0] $case[2] { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (Assemble $pathCase ($case[0]-replace' ','-')) }}
    $directoryZip=New-RawZip 'directory' @('safe/');Assert-Rejected 'directory entry' 'directory entry' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath $directoryZip -Legacy }
    Assert-Rejected 'traversal ZIP path' 'unsafe path' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (New-RawZip 'traversal' @('../escape.txt')) -Legacy };Assert-Rejected 'empty-segment ZIP path' 'unsafe path' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath (New-RawZip 'zip-empty-segment' @('review//brief.md')) -Legacy }
    $duplicateZip=New-RawZip 'duplicate' @('one.txt','one.txt');Assert-Rejected 'duplicate archive entry' 'duplicate archive entry' { & (Join-Path $root 'tools/validate_review_packet.ps1') -PacketPath $duplicateZip -Legacy }
    Write-Output 'PASS: complete malformed-fixture assertion matrix'
}
finally { Remove-Item -LiteralPath $temp -Recurse -Force }
